// <auto-generated />
using System;
using Isas.InterviewService.ApplicationDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Isas.InterviewService.Migrations
{
    [DbContext(typeof(InterviewDbContext))]
    [Migration("20260711170418_AddAnswerScoreLevelMatched")]
    partial class AddAnswerScoreLevelMatched
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Isas.InterviewService.Entities.AnswerScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnswerId")
                        .HasColumnType("uuid")
                        .HasColumnName("answer_id");

                    b.Property<int>("AttemptNo")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_no");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CriterionId")
                        .HasColumnType("uuid")
                        .HasColumnName("criterion_id");

                    b.Property<int?>("LevelMatched")
                        .HasColumnType("integer")
                        .HasColumnName("level_matched");

                    b.Property<string>("Reasoning")
                        .HasColumnType("text")
                        .HasColumnName("reasoning");

                    b.Property<int>("RubricVersion")
                        .HasColumnType("integer")
                        .HasColumnName("rubric_version");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("score");

                    b.HasKey("Id")
                        .HasName("pk_answer_scores");

                    b.HasIndex("CriterionId")
                        .HasDatabaseName("ix_answer_scores_criterion_id");

                    b.HasIndex("AnswerId", "CriterionId", "AttemptNo")
                        .IsUnique()
                        .HasDatabaseName("ix_answer_scores_answer_id_criterion_id_attempt_no");

                    b.ToTable("answer_scores", (string)null);
                });

            modelBuilder.Entity("Isas.InterviewService.Entities.CvAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CvId")
                        .HasColumnType("uuid")
                        .HasColumnName("cv_id");

                    b.Property<Guid?>("JdId")
                        .HasColumnType("uuid")
                        .HasColumnName("jd_id");

                    b.Property<string>("JdMatch")
                        .HasColumnType("jsonb")
                        .HasColumnName("jd_match");

                    b.Property<string>("JobCategory")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("job_category");

                    b.Property<string>("Strengths")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("strengths");

                    b.Property<string>("Suggestions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("suggestions");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("Weaknesses")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("weaknesses");

                    b.HasKey("Id")
                        .HasName("pk_cv_analyses");

                    b.HasIndex("CandidateId")
                        .HasDatabaseName("ix_cv_analyses_candidate_id");

                    b.ToTable("cv_analyses", (string)null);
                });

            modelBuilder.Entity("Isas.InterviewService.Entities.FileRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_type");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mime_type");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_name");

                    b.Property<string>("ParseStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("parse_status");

                    b.Property<string>("ParsedText")
                        .HasColumnType("text")
                        .HasColumnName("parsed_text");

                    b.Property<string>("StorageBucket")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_bucket");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_path");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_file_records");

                    b.ToTable("file_records", (string)null);
                });

            modelBuilder.Entity("Isas.InterviewService.Entities.PracticeAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AudioObjectKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("audio_object_key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DurationSec")
                        .HasColumnType("integer")
                        .HasColumnName("duration_sec");

                    b.Property<DateTime?>("LastScoringPublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_scoring_published_at");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Transcript")
                        .HasColumnType("text")
                        .HasColumnName("transcript");

                    b.HasKey("Id")
                        .HasName("pk_practice_answers");

                    b.HasIndex("QuestionId")
                        .IsUnique()
                        .HasDatabaseName("ix_practice_answers_question_id");

                    b.HasIndex("SessionId", "QuestionId")
                        .IsUnique()
                        .HasDatabaseName("ix_practice_answers_session_id_question_id");

                    b.ToTable("practice_answers", (string)null);
                });

            modelBuilder.Entity("Isas.InterviewService.Entities.PracticeQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("OrderNo")
                        .HasColumnType("integer")
                        .HasColumnName("order_no");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<int>("TimeLimitSec")
                        .HasColumnType("integer")
                        .HasColumnName("time_limit_sec");

                    b.HasKey("Id")
                        .HasName("pk_practice_questions");

                    b.HasIndex("SessionId", "OrderNo")
                        .IsUnique()
                        .HasDatabaseName("ix_practice_questions_session_id_order_no");

                    b.ToTable("practice_questions", (string)null);
                });

            modelBuilder.Entity("Isas.InterviewService.Entities.PracticeSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AnsweredCount")
                        .HasColumnType("integer")
                        .HasColumnName("answered_count");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CvId")
                        .HasColumnType("uuid")
                        .HasColumnName("cv_id");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline");

                    b.Property<Guid?>("JdId")
                        .HasColumnType("uuid")
                        .HasColumnName("jd_id");

                    b.Property<string>("JobCategory")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("job_category");

                    b.Property<string>("OverallComment")
                        .HasColumnType("text")
                        .HasColumnName("overall_comment");

                    b.Property<decimal?>("OverallScore")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("overall_score");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_practice_sessions");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("ix_practice_sessions_campaign_id");

                    b.HasIndex("CandidateId")
                        .HasDatabaseName("ix_practice_sessions_candidate_id");

                    b.HasIndex("CvId")
                        .HasDatabaseName("ix_practice_sessions_cv_id");

                    b.HasIndex("JdId")
                        .HasDatabaseName("ix_practice_sessions_jd_id");

                    b.ToTable("practice_sessions", (string)null);
                });

            modelBuilder.Entity("Isas.InterviewService.Entities.Roadmap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Baseline")
                        .HasColumnType("jsonb")
                        .HasColumnName("baseline");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CvId")
                        .HasColumnType("uuid")
                        .HasColumnName("cv_id");

                    b.Property<string>("FinalReport")
                        .HasColumnType("jsonb")
                        .HasColumnName("final_report");

                    b.Property<string>("JobCategory")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("job_category");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("level");

                    b.Property<string>("OverallComment")
                        .HasColumnType("text")
                        .HasColumnName("overall_comment");

                    b.Property<string>("SourceSessionIds")
                        .HasColumnType("jsonb")
                        .HasColumnName("source_session_ids");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_roadmaps");

                    b.HasIndex("CandidateId")
                        .HasDatabaseName("ix_roadmaps_candidate_id");

                    b.HasIndex("CvId")
                        .HasDatabaseName("ix_roadmaps_cv_id");

                    b.ToTable("roadmaps", (string)null);
                });

            modelBuilder.Entity("Isas.InterviewService.Entities.RoadmapLesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("MilestoneId")
                        .HasColumnType("uuid")
                        .HasColumnName("milestone_id");

                    b.Property<int>("OrderNo")
                        .HasColumnType("integer")
                        .HasColumnName("order_no");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("TheoryContent")
                        .HasColumnType("text")
                        .HasColumnName("theory_content");

                    b.Property<DateTime?>("TheoryGeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("theory_generated_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_roadmap_lessons");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_roadmap_lessons_session_id");

                    b.HasIndex("MilestoneId", "OrderNo")
                        .IsUnique()
                        .HasDatabaseName("ix_roadmap_lessons_milestone_id_order_no");

                    b.ToTable("roadmap_lessons", (string)null);
                });

            modelBuilder.Entity("Isas.InterviewService.Entities.RoadmapMilestone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("FocusCriteria")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("focus_criteria");

                    b.Property<string>("Improvement")
                        .HasColumnType("jsonb")
                        .HasColumnName("improvement");

                    b.Property<int>("OrderNo")
                        .HasColumnType("integer")
                        .HasColumnName("order_no");

                    b.Property<Guid>("RoadmapId")
                        .HasColumnType("uuid")
                        .HasColumnName("roadmap_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_roadmap_milestones");

                    b.HasIndex("RoadmapId", "OrderNo")
                        .IsUnique()
                        .HasDatabaseName("ix_roadmap_milestones_roadmap_id_order_no");

                    b.ToTable("roadmap_milestones", (string)null);
                });

            modelBuilder.Entity("Isas.InterviewService.Entities.RubricAnchor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ExampleAnswer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("example_answer");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("uuid")
                        .HasColumnName("level_id");

                    b.HasKey("Id")
                        .HasName("pk_rubric_anchors");

                    b.HasIndex("LevelId")
                        .HasDatabaseName("ix_rubric_anchors_level_id");

                    b.ToTable("rubric_anchors", (string)null);
                });

            modelBuilder.Entity("Isas.InterviewService.Entities.RubricCriterion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("JobCategory")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("job_category");

                    b.Property<int>("MaxScore")
                        .HasColumnType("integer")
                        .HasColumnName("max_score");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_rubric_criteria");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("ix_rubric_criteria_campaign_id");

                    b.HasIndex("JobCategory", "Version", "IsActive")
                        .HasDatabaseName("ix_rubric_criteria_job_category_version_is_active");

                    b.ToTable("rubric_criteria", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0b100000-0000-0000-0000-000000000001"),
                            Description = "Bóc tách, làm rõ và cấu trúc hoá yêu cầu nghiệp vụ; đặt câu hỏi đúng chỗ.",
                            IsActive = true,
                            JobCategory = "BA",
                            MaxScore = 5,
                            Name = "Phân tích yêu cầu",
                            Version = 1,
                            Weight = 0.3000m
                        },
                        new
                        {
                            Id = new Guid("0b100000-0000-0000-0000-000000000002"),
                            Description = "Diễn đạt rõ ràng, mạch lạc, đúng đối tượng người nghe.",
                            IsActive = true,
                            JobCategory = "BA",
                            MaxScore = 5,
                            Name = "Giao tiếp & trình bày",
                            Version = 1,
                            Weight = 0.2500m
                        },
                        new
                        {
                            Id = new Guid("0b100000-0000-0000-0000-000000000003"),
                            Description = "Nắm bối cảnh domain, mục tiêu và ràng buộc của các stakeholder.",
                            IsActive = true,
                            JobCategory = "BA",
                            MaxScore = 5,
                            Name = "Hiểu nghiệp vụ & các bên liên quan",
                            Version = 1,
                            Weight = 0.2500m
                        },
                        new
                        {
                            Id = new Guid("0b100000-0000-0000-0000-000000000004"),
                            Description = "Lập luận có căn cứ, cân nhắc phương án và đánh đổi.",
                            IsActive = true,
                            JobCategory = "BA",
                            MaxScore = 5,
                            Name = "Tư duy giải quyết vấn đề",
                            Version = 1,
                            Weight = 0.2000m
                        },
                        new
                        {
                            Id = new Guid("0be00000-0000-0000-0000-000000000001"),
                            Description = "Hiểu bản chất ngôn ngữ/framework, cơ chế hoạt động và trade-off kỹ thuật.",
                            IsActive = true,
                            JobCategory = "BE",
                            MaxScore = 5,
                            Name = "Chiều sâu kỹ thuật",
                            Version = 1,
                            Weight = 0.3000m
                        },
                        new
                        {
                            Id = new Guid("0be00000-0000-0000-0000-000000000002"),
                            Description = "Mô hình hoá dữ liệu, kiến trúc, khả năng mở rộng và độ tin cậy.",
                            IsActive = true,
                            JobCategory = "BE",
                            MaxScore = 5,
                            Name = "Thiết kế hệ thống & CSDL",
                            Version = 1,
                            Weight = 0.2500m
                        },
                        new
                        {
                            Id = new Guid("0be00000-0000-0000-0000-000000000003"),
                            Description = "Phân rã vấn đề, lựa chọn giải pháp hợp lý, cân nhắc độ phức tạp.",
                            IsActive = true,
                            JobCategory = "BE",
                            MaxScore = 5,
                            Name = "Giải quyết vấn đề & thuật toán",
                            Version = 1,
                            Weight = 0.2500m
                        },
                        new
                        {
                            Id = new Guid("0be00000-0000-0000-0000-000000000004"),
                            Description = "Giải thích giải pháp kỹ thuật rõ ràng, dễ theo dõi.",
                            IsActive = true,
                            JobCategory = "BE",
                            MaxScore = 5,
                            Name = "Giao tiếp & trình bày",
                            Version = 1,
                            Weight = 0.2000m
                        },
                        new
                        {
                            Id = new Guid("0fe00000-0000-0000-0000-000000000001"),
                            Description = "Nắm vững HTML/CSS/JS, framework FE, state management và hiệu năng render.",
                            IsActive = true,
                            JobCategory = "FE",
                            MaxScore = 5,
                            Name = "Chiều sâu kỹ thuật",
                            Version = 1,
                            Weight = 0.3000m
                        },
                        new
                        {
                            Id = new Guid("0fe00000-0000-0000-0000-000000000003"),
                            Description = "Xử lý bài toán UI/logic, gỡ lỗi và cân nhắc giải pháp.",
                            IsActive = true,
                            JobCategory = "FE",
                            MaxScore = 5,
                            Name = "Giải quyết vấn đề",
                            Version = 1,
                            Weight = 0.2500m
                        },
                        new
                        {
                            Id = new Guid("0fe00000-0000-0000-0000-000000000004"),
                            Description = "Diễn đạt ý tưởng và giải pháp rõ ràng, mạch lạc.",
                            IsActive = true,
                            JobCategory = "FE",
                            MaxScore = 5,
                            Name = "Giao tiếp & trình bày",
                            Version = 1,
                            Weight = 0.2500m
                        },
                        new
                        {
                            Id = new Guid("0fe00000-0000-0000-0000-000000000002"),
                            Description = "Quan tâm trải nghiệm người dùng, khả năng tiếp cận và tính nhất quán giao diện.",
                            IsActive = true,
                            JobCategory = "FE",
                            MaxScore = 5,
                            Name = "Ý thức UI/UX & accessibility",
                            Version = 1,
                            Weight = 0.2000m
                        });
                });

            modelBuilder.Entity("Isas.InterviewService.Entities.RubricLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CriterionId")
                        .HasColumnType("uuid")
                        .HasColumnName("criterion_id");

                    b.Property<string>("Descriptor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descriptor");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.HasKey("Id")
                        .HasName("pk_rubric_levels");

                    b.HasIndex("CriterionId", "Score")
                        .IsUnique()
                        .HasDatabaseName("ix_rubric_levels_criterion_id_score");

                    b.ToTable("rubric_levels", (string)null);
                });

            modelBuilder.Entity("Isas.InterviewService.Entities.SessionCriterionScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AverageScore")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("average_score");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CriterionId")
                        .HasColumnType("uuid")
                        .HasColumnName("criterion_id");

                    b.Property<string>("CriterionName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("criterion_name");

                    b.Property<int>("MaxScore")
                        .HasColumnType("integer")
                        .HasColumnName("max_score");

                    b.Property<bool>("NeedsImprovement")
                        .HasColumnType("boolean")
                        .HasColumnName("needs_improvement");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("percentage");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_session_criterion_scores");

                    b.HasIndex("CriterionId")
                        .HasDatabaseName("ix_session_criterion_scores_criterion_id");

                    b.HasIndex("SessionId", "CriterionId")
                        .IsUnique()
                        .HasDatabaseName("ix_session_criterion_scores_session_id_criterion_id");

                    b.ToTable("session_criterion_scores", (string)null);
                });

            modelBuilder.Entity("Isas.InterviewService.Entities.AnswerScore", b =>
                {
                    b.HasOne("Isas.InterviewService.Entities.PracticeAnswer", "Answer")
                        .WithMany("Scores")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_answer_scores_practice_answers_answer_id");

                    b.HasOne("Isas.InterviewService.Entities.RubricCriterion", "Criterion")
                        .WithMany()
                        .HasForeignKey("CriterionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_answer_scores_rubric_criteria_criterion_id");

                    b.Navigation("Answer");

                    b.Navigation("Criterion");
                });

            modelBuilder.Entity("Isas.InterviewService.Entities.PracticeAnswer", b =>
                {
                    b.HasOne("Isas.InterviewService.Entities.PracticeQuestion", "Question")
                        .WithOne("Answer")
                        .HasForeignKey("Isas.InterviewService.Entities.PracticeAnswer", "QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_practice_answers_practice_questions_question_id");

                    b.HasOne("Isas.InterviewService.Entities.PracticeSession", "Session")
                        .WithMany("Answers")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_practice_answers_practice_sessions_session_id");

                    b.Navigation("Question");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Isas.InterviewService.Entities.PracticeQuestion", b =>
                {
                    b.HasOne("Isas.InterviewService.Entities.PracticeSession", "Session")
                        .WithMany("Questions")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_practice_questions_practice_sessions_session_id");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Isas.InterviewService.Entities.PracticeSession", b =>
                {
                    b.HasOne("Isas.InterviewService.Entities.FileRecord", null)
                        .WithMany()
                        .HasForeignKey("CvId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_practice_sessions_file_records_cv_id");

                    b.HasOne("Isas.InterviewService.Entities.FileRecord", null)
                        .WithMany()
                        .HasForeignKey("JdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_practice_sessions_file_records_jd_id");
                });

            modelBuilder.Entity("Isas.InterviewService.Entities.Roadmap", b =>
                {
                    b.HasOne("Isas.InterviewService.Entities.FileRecord", null)
                        .WithMany()
                        .HasForeignKey("CvId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_roadmaps_file_records_cv_id");
                });

            modelBuilder.Entity("Isas.InterviewService.Entities.RoadmapLesson", b =>
                {
                    b.HasOne("Isas.InterviewService.Entities.RoadmapMilestone", "Milestone")
                        .WithMany("Lessons")
                        .HasForeignKey("MilestoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_roadmap_lessons_roadmap_milestones_milestone_id");

                    b.HasOne("Isas.InterviewService.Entities.PracticeSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_roadmap_lessons_practice_sessions_session_id");

                    b.Navigation("Milestone");
                });

            modelBuilder.Entity("Isas.InterviewService.Entities.RoadmapMilestone", b =>
                {
                    b.HasOne("Isas.InterviewService.Entities.Roadmap", "Roadmap")
                        .WithMany("Milestones")
                        .HasForeignKey("RoadmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_roadmap_milestones_roadmaps_roadmap_id");

                    b.Navigation("Roadmap");
                });

            modelBuilder.Entity("Isas.InterviewService.Entities.RubricAnchor", b =>
                {
                    b.HasOne("Isas.InterviewService.Entities.RubricLevel", "Level")
                        .WithMany("Anchors")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rubric_anchors_rubric_levels_level_id");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("Isas.InterviewService.Entities.RubricLevel", b =>
                {
                    b.HasOne("Isas.InterviewService.Entities.RubricCriterion", "Criterion")
                        .WithMany("Levels")
                        .HasForeignKey("CriterionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rubric_levels_rubric_criteria_criterion_id");

                    b.Navigation("Criterion");
                });

            modelBuilder.Entity("Isas.InterviewService.Entities.SessionCriterionScore", b =>
                {
                    b.HasOne("Isas.InterviewService.Entities.RubricCriterion", null)
                        .WithMany()
                        .HasForeignKey("CriterionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_session_criterion_scores_rubric_criteria_criterion_id");

                    b.HasOne("Isas.InterviewService.Entities.PracticeSession", "Session")
                        .WithMany("CriterionScores")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_session_criterion_scores_practice_sessions_session_id");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Isas.InterviewService.Entities.PracticeAnswer", b =>
                {
                    b.Navigation("Scores");
                });

            modelBuilder.Entity("Isas.InterviewService.Entities.PracticeQuestion", b =>
                {
                    b.Navigation("Answer");
                });

            modelBuilder.Entity("Isas.InterviewService.Entities.PracticeSession", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("CriterionScores");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Isas.InterviewService.Entities.Roadmap", b =>
                {
                    b.Navigation("Milestones");
                });

            modelBuilder.Entity("Isas.InterviewService.Entities.RoadmapMilestone", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("Isas.InterviewService.Entities.RubricCriterion", b =>
                {
                    b.Navigation("Levels");
                });

            modelBuilder.Entity("Isas.InterviewService.Entities.RubricLevel", b =>
                {
                    b.Navigation("Anchors");
                });
#pragma warning restore 612, 618
        }
    }
}
