// <auto-generated />
using System;
using Isas.InterviewService.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Isas.InterviewService.Migrations
{
    [DbContext(typeof(InterviewDbContext))]
    [Migration("20260604162119_InitPractice")]
    partial class InitPractice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Isas.InterviewService.Models.FileRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("file_type");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mime_type");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_name");

                    b.Property<string>("ParseStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("parse_status");

                    b.Property<string>("ParsedText")
                        .HasColumnType("text")
                        .HasColumnName("parsed_text");

                    b.Property<string>("StorageBucket")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("storage_bucket");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_path");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ParseStatus")
                        .HasDatabaseName("idx_files_parse_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_files_user");

                    b.HasIndex("UserId", "FileType")
                        .HasDatabaseName("idx_files_user_type");

                    b.ToTable("files", (string)null);
                });

            modelBuilder.Entity("Isas.InterviewService.Models.PracticeAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnswerType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("answer_type");

                    b.Property<Guid?>("AudioFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("audio_file_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Feedback")
                        .HasColumnType("text")
                        .HasColumnName("feedback");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<decimal?>("Score")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("score");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("TextContent")
                        .HasColumnType("text")
                        .HasColumnName("text_content");

                    b.HasKey("Id");

                    b.HasIndex("AudioFileId");

                    b.HasIndex("QuestionId")
                        .IsUnique()
                        .HasDatabaseName("idx_practice_a_question");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("idx_practice_a_session");

                    b.ToTable("practice_answers", (string)null);
                });

            modelBuilder.Entity("Isas.InterviewService.Models.PracticeQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("idx_practice_q_session");

                    b.HasIndex("SessionId", "OrderIndex")
                        .HasDatabaseName("idx_practice_q_order");

                    b.ToTable("practice_questions", (string)null);
                });

            modelBuilder.Entity("Isas.InterviewService.Models.PracticeSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("CvFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("cv_file_id");

                    b.Property<string>("Feedback")
                        .HasColumnType("text")
                        .HasColumnName("feedback");

                    b.Property<string>("JdText")
                        .HasColumnType("text")
                        .HasColumnName("jd_text");

                    b.Property<string>("JobCategory")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("job_category");

                    b.Property<DateTime?>("ScoredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scored_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("draft")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<decimal?>("TotalScore")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("total_score");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CvFileId");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_practice_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_practice_user");

                    b.ToTable("practice_sessions", (string)null);
                });

            modelBuilder.Entity("Isas.InterviewService.Models.PracticeAnswer", b =>
                {
                    b.HasOne("Isas.InterviewService.Models.FileRecord", "AudioFile")
                        .WithMany()
                        .HasForeignKey("AudioFileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Isas.InterviewService.Models.PracticeQuestion", "Question")
                        .WithOne("Answer")
                        .HasForeignKey("Isas.InterviewService.Models.PracticeAnswer", "QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AudioFile");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Isas.InterviewService.Models.PracticeQuestion", b =>
                {
                    b.HasOne("Isas.InterviewService.Models.PracticeSession", "Session")
                        .WithMany("Questions")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Isas.InterviewService.Models.PracticeSession", b =>
                {
                    b.HasOne("Isas.InterviewService.Models.FileRecord", "CvFile")
                        .WithMany()
                        .HasForeignKey("CvFileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CvFile");
                });

            modelBuilder.Entity("Isas.InterviewService.Models.PracticeQuestion", b =>
                {
                    b.Navigation("Answer");
                });

            modelBuilder.Entity("Isas.InterviewService.Models.PracticeSession", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
