services:
  isas.authservice:
    image: isas.authservice
    build:
      context: .
      dockerfile: src/services/Isas.AuthService/Dockerfile

  isas.gateway:
    image: isas.gateway
    build:
      context: .
      dockerfile: src/gateway/Isas.Gateway/Dockerfile