// <auto-generated />
using System;
using Isas.CampaignService.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Isas.CampaignService.Migrations
{
    [DbContext(typeof(CampaignDbContext))]
    [Migration("20260711101100_RenameCampaignEmployerToOrg")]
    partial class RenameCampaignEmployerToOrg
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Isas.CampaignService.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTime>("At")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("entity");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<Guid?>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("EntityId", "At")
                        .HasDatabaseName("ix_audit_logs_entity_id_at");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Isas.CampaignService.Models.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("AntiCheatEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("anti_cheat_enabled");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CriteriaFileUrl")
                        .HasColumnType("text")
                        .HasColumnName("criteria_file_url");

                    b.Property<string>("CriteriaText")
                        .HasColumnType("text")
                        .HasColumnName("criteria_text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Domain")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("domain");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("JDFileUrl")
                        .HasColumnType("text")
                        .HasColumnName("jd_file_url");

                    b.Property<string>("JDText")
                        .HasColumnType("text")
                        .HasColumnName("jd_text");

                    b.Property<string>("KeywordsAny")
                        .HasColumnType("jsonb")
                        .HasColumnName("keywords_any");

                    b.Property<int?>("MaxCandidates")
                        .HasColumnType("integer")
                        .HasColumnName("max_candidates");

                    b.Property<int?>("MinYearsExperience")
                        .HasColumnType("integer")
                        .HasColumnName("min_years_experience");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<int?>("PassScorePct")
                        .HasColumnType("integer")
                        .HasColumnName("pass_score_pct");

                    b.Property<string>("RequiredSkills")
                        .HasColumnType("jsonb")
                        .HasColumnName("required_skills");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Draft")
                        .HasColumnName("status");

                    b.Property<int?>("TimeLimitMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("time_limit_minutes");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_campaigns");

                    b.HasIndex("OrgId", "CreatedAt")
                        .HasDatabaseName("ix_campaigns_org_id_created_at");

                    b.HasIndex("OrgId", "Status")
                        .HasDatabaseName("ix_campaigns_org_id_status");

                    b.ToTable("campaigns", (string)null);
                });

            modelBuilder.Entity("Isas.CampaignService.Models.CampaignCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<Guid?>("CandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CvFileUrl")
                        .HasColumnType("text")
                        .HasColumnName("cv_file_url");

                    b.Property<string>("CvParsedText")
                        .HasColumnType("text")
                        .HasColumnName("cv_parsed_text");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<DateTime?>("LastScreeningPublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_screening_published_at");

                    b.Property<int?>("OverallMatchScore")
                        .HasColumnType("integer")
                        .HasColumnName("overall_match_score");

                    b.Property<string>("ParseStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("parse_status");

                    b.Property<string>("RejectReason")
                        .HasColumnType("text")
                        .HasColumnName("reject_reason");

                    b.Property<string>("Skills")
                        .HasColumnType("jsonb")
                        .HasColumnName("skills");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("YearsExperience")
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("years_experience");

                    b.HasKey("Id")
                        .HasName("pk_campaign_candidates");

                    b.HasIndex("CandidateId")
                        .HasDatabaseName("ix_campaign_candidates_candidate_id");

                    b.HasIndex("CampaignId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_campaign_candidates_campaign_id_email");

                    b.HasIndex("CampaignId", "Status")
                        .HasDatabaseName("ix_campaign_candidates_campaign_id_status");

                    b.ToTable("campaign_candidates", (string)null);
                });

            modelBuilder.Entity("Isas.CampaignService.Models.CampaignCriterion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("MaxScore")
                        .HasColumnType("integer")
                        .HasColumnName("max_score");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("OrderNo")
                        .HasColumnType("integer")
                        .HasColumnName("order_no");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_campaign_criteria");

                    b.HasIndex("CampaignId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_campaign_criteria_campaign_id_name");

                    b.HasIndex("CampaignId", "OrderNo")
                        .IsUnique()
                        .HasDatabaseName("ix_campaign_criteria_campaign_id_order_no");

                    b.ToTable("campaign_criteria", (string)null);
                });

            modelBuilder.Entity("Isas.CampaignService.Models.CampaignInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("CampaignCandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_candidate_id");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.HasKey("Id")
                        .HasName("pk_campaign_invitations");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("ix_campaign_invitations_campaign_id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_campaign_invitations_token");

                    b.ToTable("campaign_invitations", (string)null);
                });

            modelBuilder.Entity("Isas.CampaignService.Models.CampaignQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_required");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<int?>("TimeLimitSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("time_limit_seconds");

                    b.HasKey("Id")
                        .HasName("pk_campaign_questions");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("ix_campaign_questions_campaign_id");

                    b.ToTable("campaign_questions", (string)null);
                });

            modelBuilder.Entity("Isas.CampaignService.Models.CampaignRanking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<decimal>("TotalScore")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("total_score");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_campaign_rankings");

                    b.HasIndex("SessionId")
                        .IsUnique()
                        .HasDatabaseName("ix_campaign_rankings_session_id");

                    b.HasIndex("CampaignId", "TotalScore")
                        .HasDatabaseName("ix_campaign_rankings_campaign_id_total_score");

                    b.ToTable("campaign_rankings", (string)null);
                });

            modelBuilder.Entity("Isas.CampaignService.Models.CandidateCriterionScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CriterionId")
                        .HasColumnType("uuid")
                        .HasColumnName("criterion_id");

                    b.Property<decimal>("MatchScore")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("match_score");

                    b.Property<string>("Reasoning")
                        .HasColumnType("text")
                        .HasColumnName("reasoning");

                    b.HasKey("Id")
                        .HasName("pk_candidate_criterion_scores");

                    b.HasIndex("CriterionId")
                        .HasDatabaseName("ix_candidate_criterion_scores_criterion_id");

                    b.HasIndex("CandidateId", "CriterionId")
                        .IsUnique()
                        .HasDatabaseName("ix_candidate_criterion_scores_candidate_id_criterion_id");

                    b.ToTable("candidate_criterion_scores", (string)null);
                });

            modelBuilder.Entity("Isas.CampaignService.Models.CampaignCandidate", b =>
                {
                    b.HasOne("Isas.CampaignService.Models.Campaign", "Campaign")
                        .WithMany("Candidates")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_candidates_campaigns_campaign_id");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Isas.CampaignService.Models.CampaignCriterion", b =>
                {
                    b.HasOne("Isas.CampaignService.Models.Campaign", "Campaign")
                        .WithMany("Criteria")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_criteria_campaigns_campaign_id");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Isas.CampaignService.Models.CampaignInvitation", b =>
                {
                    b.HasOne("Isas.CampaignService.Models.Campaign", "Campaign")
                        .WithMany("Invitations")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_invitations_campaigns_campaign_id");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Isas.CampaignService.Models.CampaignQuestion", b =>
                {
                    b.HasOne("Isas.CampaignService.Models.Campaign", "Campaign")
                        .WithMany("Questions")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_questions_campaigns_campaign_id");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Isas.CampaignService.Models.CandidateCriterionScore", b =>
                {
                    b.HasOne("Isas.CampaignService.Models.CampaignCandidate", "Candidate")
                        .WithMany("CriterionScores")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_candidate_criterion_scores_campaign_candidates_candidate_id");

                    b.HasOne("Isas.CampaignService.Models.CampaignCriterion", "Criterion")
                        .WithMany()
                        .HasForeignKey("CriterionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_candidate_criterion_scores_campaign_criteria_criterion_id");

                    b.Navigation("Candidate");

                    b.Navigation("Criterion");
                });

            modelBuilder.Entity("Isas.CampaignService.Models.Campaign", b =>
                {
                    b.Navigation("Candidates");

                    b.Navigation("Criteria");

                    b.Navigation("Invitations");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Isas.CampaignService.Models.CampaignCandidate", b =>
                {
                    b.Navigation("CriterionScores");
                });
#pragma warning restore 612, 618
        }
    }
}
