// <auto-generated />
using System;
using Isas.CampaignService.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Isas.CampaignService.Migrations
{
    [DbContext(typeof(CampaignDbContext))]
    [Migration("20260711025009_AddCampaignInvitations")]
    partial class AddCampaignInvitations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Isas.CampaignService.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTime>("At")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("entity");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<Guid?>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("EntityId", "At")
                        .HasDatabaseName("ix_audit_logs_entity_id_at");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Isas.CampaignService.Models.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("AntiCheatEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("anti_cheat_enabled");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CriteriaFileUrl")
                        .HasColumnType("text")
                        .HasColumnName("criteria_file_url");

                    b.Property<string>("CriteriaText")
                        .HasColumnType("text")
                        .HasColumnName("criteria_text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Domain")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("domain");

                    b.Property<Guid>("EmployerId")
                        .HasColumnType("uuid")
                        .HasColumnName("employer_id");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("JDFileUrl")
                        .HasColumnType("text")
                        .HasColumnName("jd_file_url");

                    b.Property<string>("JDText")
                        .HasColumnType("text")
                        .HasColumnName("jd_text");

                    b.Property<int?>("MaxCandidates")
                        .HasColumnType("integer")
                        .HasColumnName("max_candidates");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Draft")
                        .HasColumnName("status");

                    b.Property<int?>("TimeLimitMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("time_limit_minutes");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_campaigns");

                    b.HasIndex("EmployerId", "CreatedAt")
                        .HasDatabaseName("ix_campaigns_employer_id_created_at");

                    b.HasIndex("EmployerId", "Status")
                        .HasDatabaseName("ix_campaigns_employer_id_status");

                    b.ToTable("campaigns", (string)null);
                });

            modelBuilder.Entity("Isas.CampaignService.Models.CampaignCriterion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("MaxScore")
                        .HasColumnType("integer")
                        .HasColumnName("max_score");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_campaign_criteria");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("ix_campaign_criteria_campaign_id");

                    b.ToTable("campaign_criteria", (string)null);
                });

            modelBuilder.Entity("Isas.CampaignService.Models.CampaignInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("CampaignCandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_candidate_id");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.HasKey("Id")
                        .HasName("pk_campaign_invitations");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("ix_campaign_invitations_campaign_id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_campaign_invitations_token");

                    b.ToTable("campaign_invitations", (string)null);
                });

            modelBuilder.Entity("Isas.CampaignService.Models.CampaignQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("EmployerId")
                        .HasColumnType("uuid")
                        .HasColumnName("employer_id");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_required");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<int?>("TimeLimitSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("time_limit_seconds");

                    b.HasKey("Id")
                        .HasName("pk_campaign_questions");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("ix_campaign_questions_campaign_id");

                    b.ToTable("campaign_questions", (string)null);
                });

            modelBuilder.Entity("Isas.CampaignService.Models.CampaignCriterion", b =>
                {
                    b.HasOne("Isas.CampaignService.Models.Campaign", "Campaign")
                        .WithMany("Criteria")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_criteria_campaigns_campaign_id");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Isas.CampaignService.Models.CampaignInvitation", b =>
                {
                    b.HasOne("Isas.CampaignService.Models.Campaign", "Campaign")
                        .WithMany("Invitations")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_invitations_campaigns_campaign_id");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Isas.CampaignService.Models.CampaignQuestion", b =>
                {
                    b.HasOne("Isas.CampaignService.Models.Campaign", "Campaign")
                        .WithMany("Questions")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_questions_campaigns_campaign_id");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Isas.CampaignService.Models.Campaign", b =>
                {
                    b.Navigation("Criteria");

                    b.Navigation("Invitations");

                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
