// <auto-generated />
using System;
using Isas.CampaignService.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Isas.CampaignService.Migrations
{
    [DbContext(typeof(CampaignDbContext))]
    partial class CampaignDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Isas.CampaignService.Models.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IncludePii")
                        .HasColumnType("boolean")
                        .HasColumnName("include_pii");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key_hash");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("key_prefix");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.HasKey("Id")
                        .HasName("pk_api_keys");

                    b.HasIndex("KeyHash")
                        .IsUnique()
                        .HasDatabaseName("ix_api_keys_key_hash");

                    b.HasIndex("OrgId", "CreatedAt")
                        .HasDatabaseName("ix_api_keys_org_id_created_at");

                    b.ToTable("api_keys", (string)null);
                });

            modelBuilder.Entity("Isas.CampaignService.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTime>("At")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("entity");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<Guid?>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("ActorUserId", "At")
                        .HasDatabaseName("ix_audit_logs_actor_user_id_at");

                    b.HasIndex("EntityId", "At")
                        .HasDatabaseName("ix_audit_logs_entity_id_at");

                    b.HasIndex("OrgId", "At")
                        .HasDatabaseName("ix_audit_logs_org_id_at");

                    b.ToTable("audit_logs", null, t =>
                        {
                            t.HasCheckConstraint("ck_audit_logs_action", "action IN ('CreateCampaign', 'EditQuestions', 'EditCriteria', 'Publish', 'Delete', 'TransitionStatus', 'Invite', 'ScreenCandidates', 'EditCandidate', 'ReissueInvitation', 'OverrideResult', 'CreateApiKey', 'RevokeApiKey')");
                        });
                });

            modelBuilder.Entity("Isas.CampaignService.Models.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("AdaptiveEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("adaptive_enabled");

                    b.Property<bool>("AntiCheatEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("anti_cheat_enabled");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CriteriaFileUrl")
                        .HasColumnType("text")
                        .HasColumnName("criteria_file_url");

                    b.Property<string>("CriteriaText")
                        .HasColumnType("text")
                        .HasColumnName("criteria_text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Domain")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("domain");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("FaceVerifyEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("face_verify_enabled");

                    b.Property<bool>("GroundingEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("grounding_enabled");

                    b.Property<string>("JDFileUrl")
                        .HasColumnType("text")
                        .HasColumnName("jd_file_url");

                    b.Property<string>("JDText")
                        .HasColumnType("text")
                        .HasColumnName("jd_text");

                    b.Property<string>("JobNeeds")
                        .HasColumnType("jsonb")
                        .HasColumnName("job_needs");

                    b.Property<string>("KeywordsAny")
                        .HasColumnType("jsonb")
                        .HasColumnName("keywords_any");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("vi")
                        .HasColumnName("language");

                    b.Property<int?>("MaxCandidates")
                        .HasColumnType("integer")
                        .HasColumnName("max_candidates");

                    b.Property<int?>("MaxConcurrentInterviews")
                        .HasColumnType("integer")
                        .HasColumnName("max_concurrent_interviews");

                    b.Property<int?>("MaxDeepPerQuestion")
                        .HasColumnType("integer")
                        .HasColumnName("max_deep_per_question");

                    b.Property<int?>("MaxFollowUps")
                        .HasColumnType("integer")
                        .HasColumnName("max_follow_ups");

                    b.Property<int?>("MaxQuestions")
                        .HasColumnType("integer")
                        .HasColumnName("max_questions");

                    b.Property<int?>("MinYearsExperience")
                        .HasColumnType("integer")
                        .HasColumnName("min_years_experience");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<int?>("PassScorePct")
                        .HasColumnType("integer")
                        .HasColumnName("pass_score_pct");

                    b.Property<int?>("QuestionsPerSession")
                        .HasColumnType("integer")
                        .HasColumnName("questions_per_session");

                    b.Property<string>("RequiredSkills")
                        .HasColumnType("jsonb")
                        .HasColumnName("required_skills");

                    b.Property<int>("RubricVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("rubric_version");

                    b.Property<DateTime?>("RubricVersionUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rubric_version_updated_at");

                    b.Property<Guid?>("RubricVersionUpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("rubric_version_updated_by");

                    b.Property<string>("Seniority")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("Junior")
                        .HasColumnName("seniority");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Draft")
                        .HasColumnName("status");

                    b.Property<int?>("TimeLimitMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("time_limit_minutes");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_campaigns");

                    b.HasIndex("OrgId", "Status")
                        .HasDatabaseName("ix_campaigns_org_id_status");

                    b.HasIndex("OrgId", "CreatedAt", "Id")
                        .HasDatabaseName("ix_campaigns_org_id_created_at_id");

                    b.ToTable("campaigns", null, t =>
                        {
                            t.HasCheckConstraint("ck_campaigns_adaptive_caps_non_negative", "(max_follow_ups IS NULL OR max_follow_ups >= 0) AND (max_questions IS NULL OR max_questions >= 0) AND (max_deep_per_question IS NULL OR max_deep_per_question >= 0)");

                            t.HasCheckConstraint("ck_campaigns_language", "language IN ('vi', 'en')");

                            t.HasCheckConstraint("ck_campaigns_pass_score_pct_range", "pass_score_pct IS NULL OR (pass_score_pct >= 0 AND pass_score_pct <= 100)");

                            t.HasCheckConstraint("ck_campaigns_questions_per_session_positive", "questions_per_session IS NULL OR questions_per_session >= 1");

                            t.HasCheckConstraint("ck_campaigns_rubric_version_positive", "rubric_version >= 1");

                            t.HasCheckConstraint("ck_campaigns_seniority", "seniority IN ('Fresher', 'Junior', 'Middle', 'Senior')");

                            t.HasCheckConstraint("ck_campaigns_status", "status IN ('Draft', 'Active', 'Closed', 'Archived')");
                        });
                });

            modelBuilder.Entity("Isas.CampaignService.Models.CampaignCriterion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("MaxScore")
                        .HasColumnType("integer")
                        .HasColumnName("max_score");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("OrderNo")
                        .HasColumnType("integer")
                        .HasColumnName("order_no");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_campaign_criteria");

                    b.HasIndex("CampaignId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_campaign_criteria_campaign_id_name");

                    b.HasIndex("CampaignId", "OrderNo")
                        .IsUnique()
                        .HasDatabaseName("ix_campaign_criteria_campaign_id_order_no");

                    b.ToTable("campaign_criteria", null, t =>
                        {
                            t.HasCheckConstraint("ck_campaign_criteria_source", "source IN ('AiSuggested', 'HrEdited', 'SystemDefault')");

                            t.HasCheckConstraint("ck_campaign_criteria_weight_range", "weight > 0 AND weight <= 1");
                        });
                });

            modelBuilder.Entity("Isas.CampaignService.Models.CampaignCriterionLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CriterionId")
                        .HasColumnType("uuid")
                        .HasColumnName("criterion_id");

                    b.Property<string>("Descriptor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descriptor");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_campaign_criterion_levels");

                    b.HasIndex("CriterionId", "Score")
                        .IsUnique()
                        .HasDatabaseName("ix_campaign_criterion_levels_criterion_id_score");

                    b.ToTable("campaign_criterion_levels", null, t =>
                        {
                            t.HasCheckConstraint("ck_campaign_criterion_levels_score_non_negative", "score >= 0");
                        });
                });

            modelBuilder.Entity("Isas.CampaignService.Models.CampaignInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("CampaignCandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_candidate_id");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("EmailSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_sent_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid?>("SlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("slot_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_campaign_invitations");

                    b.HasIndex("CampaignCandidateId")
                        .HasDatabaseName("ix_campaign_invitations_campaign_candidate_id");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("ix_campaign_invitations_campaign_id");

                    b.HasIndex("SlotId")
                        .HasDatabaseName("ix_campaign_invitations_slot_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_campaign_invitations_token_hash");

                    b.ToTable("campaign_invitations", (string)null);
                });

            modelBuilder.Entity("Isas.CampaignService.Models.CampaignMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<Guid?>("CandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CvSubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("cv_submission_id");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<DateTime?>("InterviewDeadlineAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("interview_deadline_at");

                    b.Property<DateTime?>("InterviewStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("interview_started_at");

                    b.Property<string>("InterviewStatus")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("interview_status");

                    b.Property<Guid?>("InvitationId")
                        .HasColumnType("uuid")
                        .HasColumnName("invitation_id");

                    b.Property<DateTime?>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("ReferenceImageKey")
                        .HasColumnType("text")
                        .HasColumnName("reference_image_key");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid?>("SlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("slot_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Joined")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_campaign_membership");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("ix_campaign_membership_campaign_id")
                        .HasFilter("interview_status = 'InProgress'");

                    b.HasIndex("CandidateId")
                        .HasDatabaseName("ix_campaign_membership_candidate_id");

                    b.HasIndex("CvSubmissionId")
                        .IsUnique()
                        .HasDatabaseName("ix_campaign_membership_cv_submission_id");

                    b.HasIndex("InvitationId")
                        .HasDatabaseName("ix_campaign_membership_invitation_id")
                        .HasFilter("invitation_id IS NOT NULL");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_campaign_membership_session_id")
                        .HasFilter("session_id IS NOT NULL");

                    b.HasIndex("SlotId")
                        .HasDatabaseName("ix_campaign_membership_slot_id");

                    b.HasIndex("CampaignId", "CandidateId")
                        .IsUnique()
                        .HasDatabaseName("ix_campaign_membership_campaign_id_candidate_id");

                    b.ToTable("campaign_membership", null, t =>
                        {
                            t.HasCheckConstraint("ck_campaign_membership_interview_status", "interview_status IS NULL OR interview_status IN ('NotStarted', 'InProgress', 'Abandoned', 'Completed')");

                            t.HasCheckConstraint("ck_campaign_membership_status", "status IN ('Joined')");
                        });
                });

            modelBuilder.Entity("Isas.CampaignService.Models.CampaignQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("HrEditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hr_edited_at");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_required");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("QuestionGroup")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("question_group");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_text");

                    b.Property<string>("SampleAnswer")
                        .HasColumnType("text")
                        .HasColumnName("sample_answer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_campaign_questions");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("ix_campaign_questions_campaign_id");

                    b.ToTable("campaign_questions", null, t =>
                        {
                            t.HasCheckConstraint("ck_campaign_questions_source", "source IN ('AiGenerated', 'CustomHr')");
                        });
                });

            modelBuilder.Entity("Isas.CampaignService.Models.CampaignRanking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<DateTime?>("OverriddenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("overridden_at");

                    b.Property<Guid?>("OverriddenBy")
                        .HasColumnType("uuid")
                        .HasColumnName("overridden_by");

                    b.Property<string>("OverrideNote")
                        .HasColumnType("text")
                        .HasColumnName("override_note");

                    b.Property<string>("OverrideResult")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("override_result");

                    b.Property<decimal?>("OverrideScore")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("override_score");

                    b.Property<int?>("RubricVersion")
                        .HasColumnType("integer")
                        .HasColumnName("rubric_version");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<decimal>("TotalScore")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("total_score");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_campaign_rankings");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("ix_campaign_rankings_campaign_id");

                    b.HasIndex("SessionId")
                        .IsUnique()
                        .HasDatabaseName("ix_campaign_rankings_session_id");

                    b.ToTable("campaign_rankings", (string)null);
                });

            modelBuilder.Entity("Isas.CampaignService.Models.CampaignSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.HasKey("Id")
                        .HasName("pk_campaign_slots");

                    b.HasIndex("CampaignId", "StartsAt")
                        .IsUnique()
                        .HasDatabaseName("ix_campaign_slots_campaign_id_starts_at");

                    b.ToTable("campaign_slots", null, t =>
                        {
                            t.HasCheckConstraint("ck_campaign_slots_capacity", "capacity > 0");

                            t.HasCheckConstraint("ck_campaign_slots_range", "ends_at > starts_at");
                        });
                });

            modelBuilder.Entity("Isas.CampaignService.Models.CandidateCriterionScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CriterionId")
                        .HasColumnType("uuid")
                        .HasColumnName("criterion_id");

                    b.Property<Guid>("CvSubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("cv_submission_id");

                    b.Property<decimal>("MatchScore")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("match_score");

                    b.Property<string>("Reasoning")
                        .HasColumnType("text")
                        .HasColumnName("reasoning");

                    b.HasKey("Id")
                        .HasName("pk_candidate_criterion_scores");

                    b.HasIndex("CriterionId")
                        .HasDatabaseName("ix_candidate_criterion_scores_criterion_id");

                    b.HasIndex("CvSubmissionId", "CriterionId")
                        .IsUnique()
                        .HasDatabaseName("ix_candidate_criterion_scores_cv_submission_id_criterion_id");

                    b.ToTable("candidate_criterion_scores", (string)null);
                });

            modelBuilder.Entity("Isas.CampaignService.Models.CvSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BonusSignals")
                        .HasColumnType("jsonb")
                        .HasColumnName("bonus_signals");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CvFileUrl")
                        .HasColumnType("text")
                        .HasColumnName("cv_file_url");

                    b.Property<string>("CvParsedText")
                        .HasColumnType("text")
                        .HasColumnName("cv_parsed_text");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FitSummary")
                        .HasColumnType("text")
                        .HasColumnName("fit_summary");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gaps")
                        .HasColumnType("jsonb")
                        .HasColumnName("gaps");

                    b.Property<DateTime?>("LastScreeningPublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_screening_published_at");

                    b.Property<int?>("OverallMatchScore")
                        .HasColumnType("integer")
                        .HasColumnName("overall_match_score");

                    b.Property<string>("ParseStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("parse_status");

                    b.Property<string>("RejectReason")
                        .HasColumnType("text")
                        .HasColumnName("reject_reason");

                    b.Property<int?>("ScreeningVersion")
                        .HasColumnType("integer")
                        .HasColumnName("screening_version");

                    b.Property<string>("Skills")
                        .HasColumnType("jsonb")
                        .HasColumnName("skills");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Strengths")
                        .HasColumnType("jsonb")
                        .HasColumnName("strengths");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("VerificationRisk")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("verification_risk");

                    b.Property<string>("VerifyQuestions")
                        .HasColumnType("jsonb")
                        .HasColumnName("verify_questions");

                    b.Property<decimal?>("YearsExperience")
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("years_experience");

                    b.HasKey("Id")
                        .HasName("pk_cv_submission");

                    b.HasIndex("CampaignId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_cv_submission_campaign_id_email");

                    b.HasIndex("CampaignId", "Status")
                        .HasDatabaseName("ix_cv_submission_campaign_id_status");

                    b.HasIndex("Status", "LastScreeningPublishedAt")
                        .HasDatabaseName("ix_cv_submission_status_lsp");

                    b.ToTable("cv_submission", null, t =>
                        {
                            t.HasCheckConstraint("ck_cv_submission_parse_status", "parse_status IN ('Pending', 'Done', 'Failed')");

                            t.HasCheckConstraint("ck_cv_submission_status", "status IN ('Pending', 'Filtered', 'Rejected', 'Analyzing', 'Analyzed', 'AnalysisFailed', 'Invited')");
                        });
                });

            modelBuilder.Entity("Isas.CampaignService.Models.FaceImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<DateTime>("CapturedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("storage_key");

                    b.HasKey("Id")
                        .HasName("pk_face_images");

                    b.HasIndex("CapturedAt")
                        .HasDatabaseName("ix_face_images_captured_at");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("ix_face_images_storage_key");

                    b.HasIndex("CampaignId", "SessionId")
                        .HasDatabaseName("ix_face_images_campaign_id_session_id");

                    b.ToTable("face_images", null, t =>
                        {
                            t.HasCheckConstraint("ck_face_images_kind", "kind IN ('Live', 'Reference')");
                        });
                });

            modelBuilder.Entity("Isas.CampaignService.Models.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<Guid>("InvitationId")
                        .HasColumnType("uuid")
                        .HasColumnName("invitation_id");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("PublishedAt")
                        .HasDatabaseName("ix_outbox_messages_published_at")
                        .HasFilter("published_at IS NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Isas.CampaignService.Models.RubricPreviewRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Billed")
                        .HasColumnType("boolean")
                        .HasColumnName("billed");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("ErrorReason")
                        .HasColumnType("text")
                        .HasColumnName("error_reason");

                    b.Property<bool>("LengthParityWarning")
                        .HasColumnType("boolean")
                        .HasColumnName("length_parity_warning");

                    b.Property<int?>("PromptVersion")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_version");

                    b.Property<Guid?>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_text");

                    b.Property<string>("RubricFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("rubric_fingerprint");

                    b.Property<string>("RubricSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("rubric_snapshot");

                    b.Property<int>("RubricVersion")
                        .HasColumnType("integer")
                        .HasColumnName("rubric_version");

                    b.Property<string>("Samples")
                        .HasColumnType("jsonb")
                        .HasColumnName("samples");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_rubric_preview_runs");

                    b.HasIndex("CampaignId")
                        .IsUnique()
                        .HasDatabaseName("ux_rubric_preview_runs_running")
                        .HasFilter("status = 'Running'");

                    b.HasIndex("CampaignId", "CreatedAt")
                        .HasDatabaseName("ix_rubric_preview_runs_campaign_id_created_at");

                    b.ToTable("rubric_preview_runs", null, t =>
                        {
                            t.HasCheckConstraint("ck_rubric_preview_runs_status", "status IN ('Running', 'Succeeded', 'Failed')");
                        });
                });

            modelBuilder.Entity("Isas.CampaignService.Models.SessionFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<DateTime>("DetectedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("SignalType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("signal_type");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("Client")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_session_flags");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_session_flags_session_id");

                    b.HasIndex("CampaignId", "SessionId")
                        .HasDatabaseName("ix_session_flags_campaign_id_session_id");

                    b.ToTable("session_flags", null, t =>
                        {
                            t.HasCheckConstraint("ck_session_flags_source", "source IN ('Client', 'Server')");
                        });
                });

            modelBuilder.Entity("Isas.CampaignService.Models.CampaignCriterion", b =>
                {
                    b.HasOne("Isas.CampaignService.Models.Campaign", "Campaign")
                        .WithMany("Criteria")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_criteria_campaigns_campaign_id");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Isas.CampaignService.Models.CampaignCriterionLevel", b =>
                {
                    b.HasOne("Isas.CampaignService.Models.CampaignCriterion", "Criterion")
                        .WithMany("Levels")
                        .HasForeignKey("CriterionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_criterion_levels_campaign_criteria_criterion_id");

                    b.Navigation("Criterion");
                });

            modelBuilder.Entity("Isas.CampaignService.Models.CampaignInvitation", b =>
                {
                    b.HasOne("Isas.CampaignService.Models.CvSubmission", "CvSubmission")
                        .WithMany()
                        .HasForeignKey("CampaignCandidateId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_campaign_invitations_cv_submission_campaign_candidate_id");

                    b.HasOne("Isas.CampaignService.Models.Campaign", "Campaign")
                        .WithMany("Invitations")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_invitations_campaigns_campaign_id");

                    b.HasOne("Isas.CampaignService.Models.CampaignSlot", null)
                        .WithMany()
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_campaign_invitations_campaign_slots_slot_id");

                    b.Navigation("Campaign");

                    b.Navigation("CvSubmission");
                });

            modelBuilder.Entity("Isas.CampaignService.Models.CampaignMembership", b =>
                {
                    b.HasOne("Isas.CampaignService.Models.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_membership_campaigns_campaign_id");

                    b.HasOne("Isas.CampaignService.Models.CvSubmission", "CvSubmission")
                        .WithMany()
                        .HasForeignKey("CvSubmissionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_campaign_membership_cv_submission_cv_submission_id");

                    b.HasOne("Isas.CampaignService.Models.CampaignInvitation", "Invitation")
                        .WithMany()
                        .HasForeignKey("InvitationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_campaign_membership_invitation_invitation_id");

                    b.HasOne("Isas.CampaignService.Models.CampaignSlot", null)
                        .WithMany()
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_campaign_membership_campaign_slots_slot_id");

                    b.Navigation("Campaign");

                    b.Navigation("CvSubmission");

                    b.Navigation("Invitation");
                });

            modelBuilder.Entity("Isas.CampaignService.Models.CampaignQuestion", b =>
                {
                    b.HasOne("Isas.CampaignService.Models.Campaign", "Campaign")
                        .WithMany("Questions")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_questions_campaigns_campaign_id");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Isas.CampaignService.Models.CampaignRanking", b =>
                {
                    b.HasOne("Isas.CampaignService.Models.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_rankings_campaigns_campaign_id");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Isas.CampaignService.Models.CampaignSlot", b =>
                {
                    b.HasOne("Isas.CampaignService.Models.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_slots_campaigns_campaign_id");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Isas.CampaignService.Models.CandidateCriterionScore", b =>
                {
                    b.HasOne("Isas.CampaignService.Models.CampaignCriterion", "Criterion")
                        .WithMany()
                        .HasForeignKey("CriterionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_candidate_criterion_scores_campaign_criteria_criterion_id");

                    b.HasOne("Isas.CampaignService.Models.CvSubmission", "CvSubmission")
                        .WithMany("CriterionScores")
                        .HasForeignKey("CvSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_candidate_criterion_scores_cv_submission_cv_submission_id");

                    b.Navigation("Criterion");

                    b.Navigation("CvSubmission");
                });

            modelBuilder.Entity("Isas.CampaignService.Models.CvSubmission", b =>
                {
                    b.HasOne("Isas.CampaignService.Models.Campaign", "Campaign")
                        .WithMany("CvSubmissions")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cv_submission_campaigns_campaign_id");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Isas.CampaignService.Models.RubricPreviewRun", b =>
                {
                    b.HasOne("Isas.CampaignService.Models.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rubric_preview_runs_campaigns_campaign_id");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Isas.CampaignService.Models.SessionFlag", b =>
                {
                    b.HasOne("Isas.CampaignService.Models.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_session_flags_campaigns_campaign_id");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Isas.CampaignService.Models.Campaign", b =>
                {
                    b.Navigation("Criteria");

                    b.Navigation("CvSubmissions");

                    b.Navigation("Invitations");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Isas.CampaignService.Models.CampaignCriterion", b =>
                {
                    b.Navigation("Levels");
                });

            modelBuilder.Entity("Isas.CampaignService.Models.CvSubmission", b =>
                {
                    b.Navigation("CriterionScores");
                });
#pragma warning restore 612, 618
        }
    }
}
