// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PaymentService.Models;

#nullable disable

namespace Isas.PaymentService.Migrations
{
    [DbContext(typeof(PaymentDbContext))]
    [Migration("20260805084058_AddAiUsageAudioMetering")]
    partial class AddAiUsageAudioMetering
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PaymentService.Models.AiUsageLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("AudioSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("audio_seconds");

                    b.Property<decimal>("CostUsd")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("cost_usd");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("InputPricePerMillionUsd")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("input_price_per_million_usd");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("model");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("operation");

                    b.Property<decimal>("OutputPricePerMillionUsd")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("output_price_per_million_usd");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<decimal?>("PricePerMinuteUsd")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("price_per_minute_usd");

                    b.Property<int>("PromptTokens")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_tokens");

                    b.Property<int?>("ResourceUrlsProposed")
                        .HasColumnType("integer")
                        .HasColumnName("resource_urls_proposed");

                    b.Property<int?>("ResourceUrlsRejected")
                        .HasColumnType("integer")
                        .HasColumnName("resource_urls_rejected");

                    b.Property<int>("TotalTokens")
                        .HasColumnType("integer")
                        .HasColumnName("total_tokens");

                    b.HasKey("Id")
                        .HasName("pk_ai_usage_logs");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_ai_usage_logs_created_at");

                    b.HasIndex("Operation", "CreatedAt")
                        .HasDatabaseName("ix_ai_usage_logs_operation_created_at");

                    b.ToTable("ai_usage_logs", (string)null);
                });

            modelBuilder.Entity("PaymentService.Models.CreditAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("CreditLimit")
                        .HasColumnType("integer")
                        .HasColumnName("credit_limit");

                    b.Property<int>("FreeCreditsGranted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("free_credits_granted");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("owner_type");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("Prepaid")
                        .HasColumnName("payment_mode");

                    b.Property<DateTime?>("PaymentModeChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("payment_mode_changed_at");

                    b.Property<Guid?>("PaymentModeChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_mode_changed_by");

                    b.Property<string>("PaymentModeChangedNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("payment_mode_changed_note");

                    b.Property<int?>("PeriodUsage")
                        .HasColumnType("integer")
                        .HasColumnName("period_usage");

                    b.Property<int>("RemainingCredits")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("remaining_credits");

                    b.Property<int>("ReservedCredits")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("reserved_credits");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_credit_accounts");

                    b.HasAlternateKey("OwnerType", "OwnerId")
                        .HasName("ak_credit_accounts_owner_type_owner_id");

                    b.ToTable("credit_accounts", null, t =>
                        {
                            t.HasCheckConstraint("ck_credit_accounts_credit_limit_positive", "credit_limit IS NULL OR credit_limit > 0");

                            t.HasCheckConstraint("ck_credit_accounts_enums", "owner_type IN ('Org', 'User') AND payment_mode IN ('Prepaid', 'Postpaid') AND status IN ('Active', 'Suspended')");

                            t.HasCheckConstraint("ck_credit_accounts_non_negative", "remaining_credits >= 0 AND reserved_credits >= 0 AND free_credits_granted >= 0 AND (period_usage IS NULL OR period_usage >= 0)");
                        });
                });

            modelBuilder.Entity("PaymentService.Models.CreditReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FundedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Credit")
                        .HasColumnName("funded_by");

                    b.Property<DateTime?>("MeteredPeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("metered_period_start");

                    b.Property<Guid?>("MeteredSubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("metered_subscription_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("owner_type");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("Prepaid")
                        .HasColumnName("payment_mode");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("Reserved")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_credit_reservations");

                    b.HasIndex("SessionId")
                        .IsUnique()
                        .HasDatabaseName("ix_credit_reservations_session_id");

                    b.HasIndex("OwnerType", "OwnerId")
                        .HasDatabaseName("ix_credit_reservations_owner_type_owner_id");

                    b.HasIndex("OwnerType", "OwnerId", "CreatedAt")
                        .HasDatabaseName("ix_credit_reservations_reserved")
                        .HasFilter("status = 'Reserved'");

                    b.ToTable("credit_reservations", null, t =>
                        {
                            t.HasCheckConstraint("ck_credit_reservations_enums", "owner_type IN ('Org', 'User') AND status IN ('Reserved', 'Consumed', 'Released') AND funded_by IN ('Credit', 'Subscription', 'SubscriptionMetered') AND payment_mode IN ('Prepaid', 'Postpaid')");

                            t.HasCheckConstraint("ck_reservation_metered_consistency", "(funded_by = 'SubscriptionMetered' AND metered_subscription_id IS NOT NULL AND metered_period_start IS NOT NULL) OR (funded_by <> 'SubscriptionMetered' AND metered_subscription_id IS NULL AND metered_period_start IS NULL)");
                        });
                });

            modelBuilder.Entity("PaymentService.Models.CreditTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Delta")
                        .HasColumnType("integer")
                        .HasColumnName("delta");

                    b.Property<string>("GrantIdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("grant_idempotency_key");

                    b.Property<int?>("GrantRemainingCreditsAfter")
                        .HasColumnType("integer")
                        .HasColumnName("grant_remaining_credits_after");

                    b.Property<Guid?>("GrantedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("owner_type");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("reason");

                    b.Property<Guid?>("ReversesTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("reverses_transaction_id");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id")
                        .HasName("pk_credit_transactions");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_credit_transactions_order_id");

                    b.HasIndex("ReversesTransactionId")
                        .IsUnique()
                        .HasDatabaseName("ux_credit_transactions_reverses")
                        .HasFilter("reverses_transaction_id IS NOT NULL");

                    b.HasIndex("OwnerType", "OwnerId", "GrantIdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_credit_transactions_grant_idempotency")
                        .HasFilter("grant_idempotency_key IS NOT NULL");

                    b.HasIndex("OwnerType", "OwnerId", "CreatedAt", "Id")
                        .IsDescending(false, false, true, true)
                        .HasDatabaseName("ix_credit_transactions_owner_created");

                    b.ToTable("credit_transactions", null, t =>
                        {
                            t.HasCheckConstraint("ck_credit_transactions_delta_nonzero", "delta <> 0");

                            t.HasCheckConstraint("ck_credit_transactions_enums", "owner_type IN ('Org', 'User') AND reason IN ('Purchase', 'Consume', 'Refund', 'FreeGrant', 'PromoGrant')");
                        });
                });

            modelBuilder.Entity("PaymentService.Models.HttpTrafficStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("MaxDurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("max_duration_ms");

                    b.Property<int>("Requests")
                        .HasColumnType("integer")
                        .HasColumnName("requests");

                    b.Property<string>("RouteId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("route_id");

                    b.Property<string>("StatusClass")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("status_class");

                    b.Property<long>("SumDurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("sum_duration_ms");

                    b.Property<DateTime>("WindowEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_end");

                    b.Property<DateTime>("WindowStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_start");

                    b.HasKey("Id")
                        .HasName("pk_http_traffic_stats");

                    b.HasIndex("WindowStart")
                        .HasDatabaseName("ix_http_traffic_stats_window_start");

                    b.ToTable("http_traffic_stats", (string)null);
                });

            modelBuilder.Entity("PaymentService.Models.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(16, 2)
                        .HasColumnType("numeric(16,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<int>("InterviewCount")
                        .HasColumnType("integer")
                        .HasColumnName("interview_count");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("owner_type");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_end");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_start");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("Issued")
                        .HasColumnName("status");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(16, 2)
                        .HasColumnType("numeric(16,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_invoices");

                    b.HasIndex("DueAt")
                        .HasDatabaseName("ix_invoices_issued_due_at")
                        .HasFilter("status = 'Issued'");

                    b.HasIndex("OwnerType", "OwnerId")
                        .HasDatabaseName("ix_invoices_owner_type_owner_id");

                    b.ToTable("invoices", null, t =>
                        {
                            t.HasCheckConstraint("ck_invoices_enums", "owner_type = 'Org' AND status IN ('Issued', 'Paid', 'Overdue', 'Void')");
                        });
                });

            modelBuilder.Entity("PaymentService.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("AmountVnd")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_vnd");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at");

                    b.Property<Guid?>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("CreditPack")
                        .HasColumnName("kind");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("owner_type");

                    b.Property<Guid?>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<long>("PayosOrderCode")
                        .HasColumnType("bigint")
                        .HasColumnName("payos_order_code");

                    b.Property<string>("PayoutFailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("payout_failure_reason");

                    b.Property<string>("PayoutId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("payout_id");

                    b.Property<Guid?>("PayoutIdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("payout_idempotency_key");

                    b.Property<string>("PayoutStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("payout_status");

                    b.Property<string>("RefundGatewayRef")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("refund_gateway_ref");

                    b.Property<string>("RefundReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("refund_reason");

                    b.Property<DateTime?>("RefundSettledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refund_settled_at");

                    b.Property<DateTime?>("RefundedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refunded_at");

                    b.Property<Guid?>("RefundedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("refunded_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("ExpiredAt")
                        .HasDatabaseName("ix_orders_pending_expired_at")
                        .HasFilter("status = 'Pending'");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_orders_invoice_id");

                    b.HasIndex("PackageId")
                        .HasDatabaseName("ix_orders_package_id");

                    b.HasIndex("PaidAt")
                        .HasDatabaseName("ix_orders_paid_at")
                        .HasFilter("status = 'Paid'");

                    b.HasIndex("PayosOrderCode")
                        .IsUnique()
                        .HasDatabaseName("ix_orders_payos_order_code");

                    b.HasIndex("PayoutIdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_orders_payout_idempotency_key")
                        .HasFilter("payout_idempotency_key IS NOT NULL");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_orders_payout_in_flight")
                        .HasFilter("payout_status = 'InFlight'");

                    b.HasIndex("CreatedAt", "Id")
                        .IsDescending()
                        .HasDatabaseName("ix_orders_created_id_desc");

                    b.HasIndex("OwnerType", "OwnerId", "CreatedAt", "Id")
                        .IsDescending(false, false, true, true)
                        .HasDatabaseName("ix_orders_owner_created");

                    b.ToTable("orders", null, t =>
                        {
                            t.HasCheckConstraint("ck_orders_amount_non_negative", "amount_vnd >= 0");

                            t.HasCheckConstraint("ck_orders_kind", "kind IN ('CreditPack', 'InvoiceSettlement', 'SubscriptionPurchase', 'SubscriptionRenewal')");

                            t.HasCheckConstraint("ck_orders_owner_type", "owner_type IN ('Org', 'User')");

                            t.HasCheckConstraint("ck_orders_payout_status", "payout_status IS NULL OR payout_status IN ('InFlight', 'Succeeded', 'Failed')");

                            t.HasCheckConstraint("ck_orders_status", "status IN ('Pending', 'Paid', 'Failed', 'Expired', 'Cancelled', 'Refunded')");
                        });
                });

            modelBuilder.Entity("PaymentService.Models.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Gateway")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("payos")
                        .HasColumnName("gateway");

                    b.Property<string>("GatewayTxnId")
                        .HasColumnType("text")
                        .HasColumnName("gateway_txn_id");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("RawWebhookPayload")
                        .HasColumnType("text")
                        .HasColumnName("raw_webhook_payload");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_payment_transactions");

                    b.HasIndex("OrderId", "CreatedAt")
                        .HasDatabaseName("ix_payment_transactions_order_id_created_at");

                    b.ToTable("payment_transactions", (string)null);
                });

            modelBuilder.Entity("PaymentService.Models.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("AdaptiveEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("adaptive_enabled");

                    b.Property<int?>("AdaptiveMaxFollowups")
                        .HasColumnType("integer")
                        .HasColumnName("adaptive_max_followups");

                    b.Property<int?>("AdaptiveMaxQuestions")
                        .HasColumnType("integer")
                        .HasColumnName("adaptive_max_questions");

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("audience");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("CvAnalysisIncluded")
                        .HasColumnType("boolean")
                        .HasColumnName("cv_analysis_included");

                    b.Property<string>("EntitlementsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("entitlements_json");

                    b.Property<int>("EntitlementsVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("entitlements_version");

                    b.Property<bool>("GroundingEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("grounding_enabled");

                    b.Property<string>("InterviewFunding")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("interview_funding");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int?>("MaxActiveCampaigns")
                        .HasColumnType("integer")
                        .HasColumnName("max_active_campaigns");

                    b.Property<int?>("MaxCandidatesCap")
                        .HasColumnType("integer")
                        .HasColumnName("max_candidates_cap");

                    b.Property<int?>("MaxQuestionsCap")
                        .HasColumnType("integer")
                        .HasColumnName("max_questions_cap");

                    b.Property<int?>("MonthlyQuota")
                        .HasColumnType("integer")
                        .HasColumnName("monthly_quota");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<bool>("PostpaidEligible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("postpaid_eligible");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<bool>("RepoAnalysisIncluded")
                        .HasColumnType("boolean")
                        .HasColumnName("repo_analysis_included");

                    b.Property<bool>("RoadmapEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("roadmap_enabled");

                    b.Property<int?>("SeatCount")
                        .HasColumnType("integer")
                        .HasColumnName("seat_count");

                    b.Property<int>("SelfConsistencyN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("self_consistency_n");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_plans");

                    b.HasIndex("Audience", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_plans_audience_code");

                    b.HasIndex("Audience", "IsActive")
                        .HasDatabaseName("ix_plans_audience_active");

                    b.ToTable("plans", null, t =>
                        {
                            t.HasCheckConstraint("ck_plans_adaptive_caps", "adaptive_enabled OR (adaptive_max_questions IS NULL AND adaptive_max_followups IS NULL)");

                            t.HasCheckConstraint("ck_plans_audience", "audience IN ('B2C', 'B2B')");

                            t.HasCheckConstraint("ck_plans_b2c_no_b2b", "audience = 'B2B' OR (max_active_campaigns IS NULL AND max_candidates_cap IS NULL AND postpaid_eligible = false AND seat_count IS NULL)");

                            t.HasCheckConstraint("ck_plans_funding", "interview_funding IN ('Credit', 'Metered', 'Unlimited')");

                            t.HasCheckConstraint("ck_plans_maxq", "max_questions_cap IS NULL OR max_questions_cap BETWEEN 0 AND 20");

                            t.HasCheckConstraint("ck_plans_metered", "interview_funding <> 'Metered' OR monthly_quota > 0");

                            t.HasCheckConstraint("ck_plans_scn", "self_consistency_n >= 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            AdaptiveEnabled = false,
                            Audience = "B2C",
                            Code = "free",
                            CreatedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CvAnalysisIncluded = false,
                            EntitlementsJson = "[]",
                            EntitlementsVersion = 1,
                            GroundingEnabled = false,
                            InterviewFunding = "Credit",
                            IsActive = true,
                            Name = "Free",
                            PostpaidEligible = false,
                            Rank = 0,
                            RepoAnalysisIncluded = false,
                            RoadmapEnabled = false,
                            SelfConsistencyN = 1,
                            UpdatedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            AdaptiveEnabled = true,
                            AdaptiveMaxFollowups = 3,
                            AdaptiveMaxQuestions = 10,
                            Audience = "B2C",
                            Code = "plus",
                            CreatedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CvAnalysisIncluded = true,
                            EntitlementsJson = "[]",
                            EntitlementsVersion = 1,
                            GroundingEnabled = true,
                            InterviewFunding = "Metered",
                            IsActive = true,
                            MaxQuestionsCap = 10,
                            MonthlyQuota = 30,
                            Name = "Plus",
                            PostpaidEligible = false,
                            Rank = 1,
                            RepoAnalysisIncluded = false,
                            RoadmapEnabled = true,
                            SelfConsistencyN = 1,
                            UpdatedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            AdaptiveEnabled = true,
                            AdaptiveMaxFollowups = 5,
                            AdaptiveMaxQuestions = 20,
                            Audience = "B2C",
                            Code = "pro",
                            CreatedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CvAnalysisIncluded = true,
                            EntitlementsJson = "[]",
                            EntitlementsVersion = 1,
                            GroundingEnabled = true,
                            InterviewFunding = "Metered",
                            IsActive = true,
                            MaxQuestionsCap = 20,
                            MonthlyQuota = 100,
                            Name = "Pro",
                            PostpaidEligible = false,
                            Rank = 2,
                            RepoAnalysisIncluded = true,
                            RoadmapEnabled = true,
                            SelfConsistencyN = 3,
                            UpdatedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            AdaptiveEnabled = false,
                            Audience = "B2B",
                            Code = "starter",
                            CreatedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CvAnalysisIncluded = false,
                            EntitlementsJson = "[]",
                            EntitlementsVersion = 1,
                            GroundingEnabled = false,
                            InterviewFunding = "Credit",
                            IsActive = true,
                            MaxActiveCampaigns = 1,
                            MaxCandidatesCap = 25,
                            Name = "Starter",
                            PostpaidEligible = false,
                            Rank = 0,
                            RepoAnalysisIncluded = false,
                            RoadmapEnabled = false,
                            SeatCount = 1,
                            SelfConsistencyN = 1,
                            UpdatedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            AdaptiveEnabled = true,
                            Audience = "B2B",
                            Code = "business",
                            CreatedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CvAnalysisIncluded = false,
                            EntitlementsJson = "[]",
                            EntitlementsVersion = 1,
                            GroundingEnabled = true,
                            InterviewFunding = "Credit",
                            IsActive = true,
                            MaxActiveCampaigns = 10,
                            MaxCandidatesCap = 200,
                            Name = "Business",
                            PostpaidEligible = true,
                            Rank = 1,
                            RepoAnalysisIncluded = false,
                            RoadmapEnabled = false,
                            SeatCount = 10,
                            SelfConsistencyN = 1,
                            UpdatedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            AdaptiveEnabled = true,
                            Audience = "B2B",
                            Code = "enterprise",
                            CreatedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CvAnalysisIncluded = false,
                            EntitlementsJson = "[]",
                            EntitlementsVersion = 1,
                            GroundingEnabled = true,
                            InterviewFunding = "Credit",
                            IsActive = true,
                            Name = "Enterprise",
                            PostpaidEligible = true,
                            Rank = 2,
                            RepoAnalysisIncluded = false,
                            RoadmapEnabled = false,
                            SelfConsistencyN = 1,
                            UpdatedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("PaymentService.Models.ProductPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Audience")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("audience");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("DurationDays")
                        .HasColumnType("integer")
                        .HasColumnName("duration_days");

                    b.Property<int?>("InterviewCredits")
                        .HasColumnType("integer")
                        .HasColumnName("interview_credits");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<long>("PriceVnd")
                        .HasColumnType("bigint")
                        .HasColumnName("price_vnd");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_product_packages");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("ix_product_packages_plan_id");

                    b.ToTable("product_packages", null, t =>
                        {
                            t.HasCheckConstraint("ck_product_packages_audience", "audience IS NULL OR audience IN ('B2C', 'B2B')");

                            t.HasCheckConstraint("ck_product_packages_price_non_negative", "price_vnd >= 0");

                            t.HasCheckConstraint("ck_product_packages_type", "type IN ('OneTime', 'Subscription')");
                        });
                });

            modelBuilder.Entity("PaymentService.Models.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("ActivatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("AdminGrantIdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("admin_grant_idempotency_key");

                    b.Property<string>("Audience")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasDefaultValue("B2C")
                        .HasColumnName("audience");

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("billing_cycle");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EntitlementHash")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("")
                        .HasColumnName("entitlement_hash");

                    b.Property<string>("EntitlementSnapshot")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("entitlement_snapshot");

                    b.Property<int>("EntitlementsVersion")
                        .HasColumnType("integer")
                        .HasColumnName("entitlements_version");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("InterviewFunding")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("Credit")
                        .HasColumnName("interview_funding");

                    b.Property<short?>("MeterAnchorDay")
                        .HasColumnType("smallint")
                        .HasColumnName("meter_anchor_day");

                    b.Property<int?>("MonthlyQuota")
                        .HasColumnType("integer")
                        .HasColumnName("monthly_quota");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("owner_type");

                    b.Property<Guid?>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<Guid?>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("Purchase")
                        .HasColumnName("source");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<string>("TierCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("")
                        .HasColumnName("tier_code");

                    b.Property<int>("TierRank")
                        .HasColumnType("integer")
                        .HasColumnName("tier_rank");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_subscriptions");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_subscriptions_active_expires_at")
                        .HasFilter("status = 'Active'");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_subscriptions_order_id")
                        .HasFilter("order_id IS NOT NULL");

                    b.HasIndex("PackageId")
                        .HasDatabaseName("ix_subscriptions_package_id");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("ix_subscriptions_plan_id");

                    b.HasIndex("OwnerType", "OwnerId", "AdminGrantIdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_subscriptions_owner_grant_idempotency")
                        .HasFilter("admin_grant_idempotency_key IS NOT NULL");

                    b.HasIndex("OwnerType", "OwnerId", "ExpiresAt")
                        .HasDatabaseName("ix_subscriptions_owner_active")
                        .HasFilter("status = 'Active'");

                    b.ToTable("subscriptions", null, t =>
                        {
                            t.HasCheckConstraint("ck_sub_audience_owner", "(audience = 'B2C' AND owner_type = 'User') OR (audience = 'B2B' AND owner_type = 'Org')");

                            t.HasCheckConstraint("ck_sub_meter_anchor", "meter_anchor_day IS NULL OR meter_anchor_day BETWEEN 1 AND 28");

                            t.HasCheckConstraint("ck_sub_metered_quota", "interview_funding <> 'Metered' OR monthly_quota IS NOT NULL AND monthly_quota > 0");

                            t.HasCheckConstraint("ck_subscriptions_enums", "billing_cycle IN ('Monthly', 'Annual') AND status IN ('Active', 'Expired', 'Cancelled') AND audience IN ('B2C', 'B2B') AND interview_funding IN ('Credit', 'Metered', 'Unlimited') AND source IN ('Purchase', 'AdminGrant')");

                            t.HasCheckConstraint("ck_subscriptions_period_positive", "expires_at > started_at");
                        });
                });

            modelBuilder.Entity("PaymentService.Models.SubscriptionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("event_type");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("payload");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.HasKey("Id")
                        .HasName("pk_subscription_events");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("ix_subscription_events_subscription_id");

                    b.ToTable("subscription_events", (string)null);
                });

            modelBuilder.Entity("PaymentService.Models.SubscriptionMeter", b =>
                {
                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_start");

                    b.Property<int>("ReservedCount")
                        .HasColumnType("integer")
                        .HasColumnName("reserved_count");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("UsedCount")
                        .HasColumnType("integer")
                        .HasColumnName("used_count");

                    b.HasKey("SubscriptionId", "PeriodStart")
                        .HasName("pk_subscription_meters");

                    b.ToTable("subscription_meters", null, t =>
                        {
                            t.HasCheckConstraint("ck_meter_nonneg", "used_count >= 0 AND reserved_count >= 0");
                        });
                });

            modelBuilder.Entity("PaymentService.Models.CreditReservation", b =>
                {
                    b.HasOne("PaymentService.Models.CreditAccount", null)
                        .WithMany()
                        .HasForeignKey("OwnerType", "OwnerId")
                        .HasPrincipalKey("OwnerType", "OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_credit_reservations_credit_accounts_owner_type_owner_id");
                });

            modelBuilder.Entity("PaymentService.Models.CreditTransaction", b =>
                {
                    b.HasOne("PaymentService.Models.Order", "Order")
                        .WithMany("CreditTransactions")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_credit_transactions_orders_order_id");

                    b.HasOne("PaymentService.Models.CreditTransaction", "ReversesTransaction")
                        .WithMany()
                        .HasForeignKey("ReversesTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_credit_transactions_credit_transactions_reverses_transactio");

                    b.HasOne("PaymentService.Models.CreditAccount", null)
                        .WithMany()
                        .HasForeignKey("OwnerType", "OwnerId")
                        .HasPrincipalKey("OwnerType", "OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_credit_transactions_credit_accounts_owner_type_owner_id");

                    b.Navigation("Order");

                    b.Navigation("ReversesTransaction");
                });

            modelBuilder.Entity("PaymentService.Models.Invoice", b =>
                {
                    b.HasOne("PaymentService.Models.CreditAccount", null)
                        .WithMany()
                        .HasForeignKey("OwnerType", "OwnerId")
                        .HasPrincipalKey("OwnerType", "OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invoices_credit_accounts_owner_type_owner_id");
                });

            modelBuilder.Entity("PaymentService.Models.Order", b =>
                {
                    b.HasOne("PaymentService.Models.Invoice", "Invoice")
                        .WithMany("Orders")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_orders_invoices_invoice_id");

                    b.HasOne("PaymentService.Models.ProductPackage", "Package")
                        .WithMany("Orders")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_orders_product_packages_package_id");

                    b.Navigation("Invoice");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("PaymentService.Models.PaymentTransaction", b =>
                {
                    b.HasOne("PaymentService.Models.Order", "Order")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_payment_transactions_orders_order_id");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PaymentService.Models.ProductPackage", b =>
                {
                    b.HasOne("PaymentService.Models.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_product_packages_plans_plan_id");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("PaymentService.Models.Subscription", b =>
                {
                    b.HasOne("PaymentService.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_subscriptions_orders_order_id");

                    b.HasOne("PaymentService.Models.ProductPackage", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_subscriptions_product_packages_package_id");

                    b.HasOne("PaymentService.Models.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_subscriptions_plans_plan_id");

                    b.HasOne("PaymentService.Models.CreditAccount", null)
                        .WithMany()
                        .HasForeignKey("OwnerType", "OwnerId")
                        .HasPrincipalKey("OwnerType", "OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_credit_accounts_owner_type_owner_id");

                    b.Navigation("Order");

                    b.Navigation("Package");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("PaymentService.Models.SubscriptionEvent", b =>
                {
                    b.HasOne("PaymentService.Models.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subscription_events_subscriptions_subscription_id");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("PaymentService.Models.SubscriptionMeter", b =>
                {
                    b.HasOne("PaymentService.Models.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subscription_meters_subscriptions_subscription_id");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("PaymentService.Models.Invoice", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("PaymentService.Models.Order", b =>
                {
                    b.Navigation("CreditTransactions");

                    b.Navigation("PaymentTransactions");
                });

            modelBuilder.Entity("PaymentService.Models.ProductPackage", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
