// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PaymentService.Models;

#nullable disable

namespace Isas.PaymentService.Migrations
{
    [DbContext(typeof(PaymentDbContext))]
    [Migration("20260717102711_AddDb5SweeperIndexes")]
    partial class AddDb5SweeperIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PaymentService.Models.CreditAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("CreditLimit")
                        .HasColumnType("integer")
                        .HasColumnName("credit_limit");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("owner_type");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("Prepaid")
                        .HasColumnName("payment_mode");

                    b.Property<int?>("PeriodUsage")
                        .HasColumnType("integer")
                        .HasColumnName("period_usage");

                    b.Property<int>("RemainingCredits")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("remaining_credits");

                    b.Property<int>("ReservedCredits")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("reserved_credits");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_credit_accounts");

                    b.HasAlternateKey("OwnerType", "OwnerId")
                        .HasName("ak_credit_accounts_owner_type_owner_id");

                    b.ToTable("credit_accounts", null, t =>
                        {
                            t.HasCheckConstraint("ck_credit_accounts_non_negative", "remaining_credits >= 0 AND reserved_credits >= 0 AND (period_usage IS NULL OR period_usage >= 0)");
                        });
                });

            modelBuilder.Entity("PaymentService.Models.CreditReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("owner_type");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("Reserved")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_credit_reservations");

                    b.HasIndex("SessionId")
                        .IsUnique()
                        .HasDatabaseName("ix_credit_reservations_session_id");

                    b.HasIndex("OwnerType", "OwnerId")
                        .HasDatabaseName("ix_credit_reservations_owner_type_owner_id");

                    b.HasIndex("OwnerType", "OwnerId", "CreatedAt")
                        .HasDatabaseName("ix_credit_reservations_reserved")
                        .HasFilter("status = 'Reserved'");

                    b.ToTable("credit_reservations", (string)null);
                });

            modelBuilder.Entity("PaymentService.Models.CreditTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Delta")
                        .HasColumnType("integer")
                        .HasColumnName("delta");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("owner_type");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("reason");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id")
                        .HasName("pk_credit_transactions");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_credit_transactions_order_id");

                    b.HasIndex("OwnerType", "OwnerId")
                        .HasDatabaseName("ix_credit_transactions_owner_type_owner_id");

                    b.ToTable("credit_transactions", null, t =>
                        {
                            t.HasCheckConstraint("ck_credit_transactions_delta_nonzero", "delta <> 0");
                        });
                });

            modelBuilder.Entity("PaymentService.Models.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(16, 2)
                        .HasColumnType("numeric(16,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("InterviewCount")
                        .HasColumnType("integer")
                        .HasColumnName("interview_count");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("owner_type");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_end");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_start");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("Issued")
                        .HasColumnName("status");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(16, 2)
                        .HasColumnType("numeric(16,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_invoices");

                    b.HasIndex("OwnerType", "OwnerId")
                        .HasDatabaseName("ix_invoices_owner_type_owner_id");

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("PaymentService.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("AmountVnd")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_vnd");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at");

                    b.Property<Guid?>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("CreditPack")
                        .HasColumnName("kind");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("owner_type");

                    b.Property<Guid?>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<long>("PayosOrderCode")
                        .HasColumnType("bigint")
                        .HasColumnName("payos_order_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_orders_invoice_id");

                    b.HasIndex("PackageId")
                        .HasDatabaseName("ix_orders_package_id");

                    b.HasIndex("PayosOrderCode")
                        .IsUnique()
                        .HasDatabaseName("ix_orders_payos_order_code");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("PaymentService.Models.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Gateway")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("payos")
                        .HasColumnName("gateway");

                    b.Property<string>("GatewayTxnId")
                        .HasColumnType("text")
                        .HasColumnName("gateway_txn_id");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("RawWebhookPayload")
                        .HasColumnType("text")
                        .HasColumnName("raw_webhook_payload");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_payment_transactions");

                    b.HasIndex("OrderId", "CreatedAt")
                        .HasDatabaseName("ix_payment_transactions_order_id_created_at");

                    b.ToTable("payment_transactions", (string)null);
                });

            modelBuilder.Entity("PaymentService.Models.ProductPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("DurationDays")
                        .HasColumnType("integer")
                        .HasColumnName("duration_days");

                    b.Property<int?>("InterviewCredits")
                        .HasColumnType("integer")
                        .HasColumnName("interview_credits");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("PriceVnd")
                        .HasColumnType("bigint")
                        .HasColumnName("price_vnd");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_product_packages");

                    b.ToTable("product_packages", (string)null);
                });

            modelBuilder.Entity("PaymentService.Models.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_subscriptions");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_subscriptions_order_id");

                    b.HasIndex("PackageId")
                        .HasDatabaseName("ix_subscriptions_package_id");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("PaymentService.Models.CreditReservation", b =>
                {
                    b.HasOne("PaymentService.Models.CreditAccount", null)
                        .WithMany()
                        .HasForeignKey("OwnerType", "OwnerId")
                        .HasPrincipalKey("OwnerType", "OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_credit_reservations_credit_accounts_owner_type_owner_id");
                });

            modelBuilder.Entity("PaymentService.Models.CreditTransaction", b =>
                {
                    b.HasOne("PaymentService.Models.Order", "Order")
                        .WithMany("CreditTransactions")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_credit_transactions_orders_order_id");

                    b.HasOne("PaymentService.Models.CreditAccount", null)
                        .WithMany()
                        .HasForeignKey("OwnerType", "OwnerId")
                        .HasPrincipalKey("OwnerType", "OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_credit_transactions_credit_accounts_owner_type_owner_id");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PaymentService.Models.Invoice", b =>
                {
                    b.HasOne("PaymentService.Models.CreditAccount", null)
                        .WithMany()
                        .HasForeignKey("OwnerType", "OwnerId")
                        .HasPrincipalKey("OwnerType", "OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invoices_credit_accounts_owner_type_owner_id");
                });

            modelBuilder.Entity("PaymentService.Models.Order", b =>
                {
                    b.HasOne("PaymentService.Models.Invoice", "Invoice")
                        .WithMany("Orders")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_orders_invoices_invoice_id");

                    b.HasOne("PaymentService.Models.ProductPackage", "Package")
                        .WithMany("Orders")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_orders_product_packages_package_id");

                    b.Navigation("Invoice");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("PaymentService.Models.PaymentTransaction", b =>
                {
                    b.HasOne("PaymentService.Models.Order", "Order")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_payment_transactions_orders_order_id");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PaymentService.Models.Subscription", b =>
                {
                    b.HasOne("PaymentService.Models.Order", "Order")
                        .WithOne("Subscription")
                        .HasForeignKey("PaymentService.Models.Subscription", "OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_orders_order_id");

                    b.HasOne("PaymentService.Models.ProductPackage", "Package")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_product_packages_package_id");

                    b.Navigation("Order");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("PaymentService.Models.Invoice", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("PaymentService.Models.Order", b =>
                {
                    b.Navigation("CreditTransactions");

                    b.Navigation("PaymentTransactions");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("PaymentService.Models.ProductPackage", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
